### ISSUE TITLE
Not an issue, small query on the API testing

### ISSUE THREAD

**Issue by vishnuprakash9845** [hkamel/azuredevops-postman-collections#18]
New to the field of Azure devops, so I started to test the API using postman manually. I am planning to do the API service testing automatically and create pipeline in azure devops. So how do i integrate the postman API's in azure devops pipeline.  Can anyone help me on this please.

**Comment by hkamel** [comment]
This is a good reference [How to Configure postman / newman API tests in Azure DevOps or TFS and Publish HTML Results?](https://medium.com/@ganeshsirsi/how-to-configure-postman-newman-api-tests-in-azure-devops-or-tfs-and-publish-html-results-caf60a25c8b9)
